### ISSUE TITLE
Design user interface for iPhone devices 

### ISSUE THREAD

**Issue by seinmon** [seinmon/world-clock-alarm#1]
### Why / Problem:
Create a basic user interface for the project using the interface builder. Create a `TabBarController` with two tabs, namely *World Clock* and *Reminders*. Each tab should be designed in separate storyboards.
 
### Acceptance Criteria:
The `Views` are customized and users must be able to navigate through the app.

### Additional Context:
**Sub-issues:**
- [x] Create `Main.storyboard` #4
- [X] Create `WorldClock.storyboard` #5 
- [ ] Create `NewTimezone.storyboard` #5 
- [X] Create `Reminders.storyboard` #6 
- [ ] Create `NewReminder.storyboard` #7
