### ISSUE TITLE
World Clock tab

### ISSUE THREAD

**Issue by seinmon** [seinmon/world-clock-alarm#12]
### Why / Problem:
Some people might want to see the time in a different timezone, without creating a reminder. They must be able to add cities and change the title of each item to something meaningful. For instance, they should be able to add *New York City* in the World Clocks and change its title to *Parents' Place*.

### Acceptance Criteria:
Users can create new timezone items, set a title, sort, and delete items.

### Additional Context:
**Checklist**
- [ ] Adding new timezone
- [ ] Deleting world clock items
- [ ] Sorting world clock items
- [ ] Renaming world clock items
