### ISSUE TITLE
Create Main.storyboard

### ISSUE THREAD

**Issue by seinmon** [seinmon/world-clock-alarm#2]
## Main.storyboard Description

Main.storyboard is the storyboard file that contains the initial view controller of the app. Relationship between high level destinations are represented in this file, even though each have their own separate storyboard file. 

## Proposed Solution
In order to avoid merge conflicts, user interface and the sub-scenes of each high level destination is designed in a separate storyboard file. First, we create a `TabBarViewController` in the `Main.storyboard` with two distinct `storyboard references` as its `ViewControllers`. Each of these `storyboard references` point to a different storyboard file, which contains the design of the respective tab.

## Checklist

- [ ] Create `Main.storyboard`
- [ ] Create [`WorldClock.storyboard`](#4)
- [ ] Create [`Reminders.storyboard`](#5)
