### ISSUE TITLE
Reminders tab

### ISSUE THREAD

**Issue by seinmon** [seinmon/world-clock-alarm#21]
### Acceptance Criteria:
Users can create reminders in different timezones and receive notifications for their reminders.

### Additional Context:
**Sub-issues**
- [ ] Create new reminder # 
- [ ] Use timezones as section titles # 
- [ ] Sort reminders based on date/time # 
- [ ] Deleting reminders #
